using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

namespace Project_01
{
    public partial class PrescriptionForm : Form
    {
        public string AppointmentID;
        private string patientId;
        private string patientName;
        private string doctorId;

        public PrescriptionForm()
        {
            InitializeComponent();
        }

        private void PrescriptionForm_Load(object sender, EventArgs e)
        {
            LoadAppointmentInfo();
            LoadMedicines();
        }

        private void LoadAppointmentInfo()
        {
            SqlConnection con = dbConnection.GetConnection();
            string query = @"SELECT p.patientID, p.userName, a.appoinmentDate, a.doctorID
                             FROM appoinment a
                             INNER JOIN patient p ON a.patientID = p.patientID
                             WHERE a.appointmentID = @id";
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.Parameters.AddWithValue("@id", AppointmentID);
            con.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.Read())
            {
                patientId = dr["patientID"].ToString();
                patientName = dr["userName"].ToString();
                doctorId = dr["doctorID"].ToString();
                DateTime aptDate = Convert.ToDateTime(dr["appoinmentDate"]);
                lblApptInfo.Text = $"Appointment #{AppointmentID}  |  {patientName}  |  {aptDate:MMM dd, yyyy}";
            }
            con.Close();
        }

        private void LoadMedicines()
        {
            SqlConnection con = dbConnection.GetConnection();
            string query = "SELECT medicine_name FROM medicine ORDER BY medicine_name";
            SqlCommand cmd = new SqlCommand(query, con);
            con.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                cmbMedicine.Items.Add(dr["medicine_name"].ToString());
            }
            con.Close();
            if (cmbMedicine.Items.Count > 0)
                cmbMedicine.SelectedIndex = 0;
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            if (!string.IsNullOrEmpty(cmbMedicine.Text))
            {
                string med = cmbMedicine.Text;
                string dosage = cmbDosage.Text.Trim();
                if (string.IsNullOrEmpty(dosage))
                    dosage = "As directed";
                lstDrugs.Items.Add($"{med} | {dosage}");
                cmbMedicine.Focus();
                cmbDosage.Text = "";
            }
        }

        private void btnRemove_Click(object sender, EventArgs e)
        {
            if (lstDrugs.SelectedIndex >= 0)
                lstDrugs.Items.RemoveAt(lstDrugs.SelectedIndex);
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (lstDrugs.Items.Count == 0 && string.IsNullOrWhiteSpace(txtDescription.Text))
            {
                MessageBox.Show("Please add at least one medicine or instructions.", "Incomplete Prescription", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            SqlConnection con = dbConnection.GetConnection();
            con.Open();

            // Insert into prescriptions table (prescriptionID autogenerated here)
            // Generate short prescription ID that fits in VARCHAR(10): "PR" + 8 hex chars from GUID
            string prescriptionId = "PR" + Guid.NewGuid().ToString().Replace("-", "").Substring(0, 8).ToUpper();
            string sql = @"INSERT INTO prescriptions (prescriptionID, patientID, appoinmentID, doctorID, date) VALUES (@prescId, @patientId, @apptId, @doctorId, @date)";
            SqlCommand cmd = new SqlCommand(sql, con);
            cmd.Parameters.AddWithValue("@prescId", prescriptionId);
            cmd.Parameters.AddWithValue("@patientId", (object)patientId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@apptId", AppointmentID.ToString());
            cmd.Parameters.AddWithValue("@doctorId", (object)doctorId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@date", DateTime.Now);
            cmd.ExecuteNonQuery();

            // Insert prescription details for each selected medicine (map name->id)
            foreach (var item in lstDrugs.Items)
            {
                string itemStr = item.ToString();
                string medName = itemStr;
                string dosage = "";
                int sep = itemStr.IndexOf(" | ");
                if (sep >= 0)
                {
                    medName = itemStr.Substring(0, sep);
                    dosage = itemStr.Substring(sep + 3);
                }

                // get medicine_id from medicine table
                string getMed = "SELECT medicine_id FROM medicine WHERE medicine_name = @mname";
                SqlCommand cmdMed = new SqlCommand(getMed, con);
                cmdMed.Parameters.AddWithValue("@mname", medName);
                object medObj = cmdMed.ExecuteScalar();
                string medId = medObj != null ? medObj.ToString() : null;

                string insertDetail = "INSERT INTO prescriptionDetails (ID, prescriptionID, medicineID, dosage) VALUES (@id, @prescId, @medId, @dosage)";
                SqlCommand cmdDetail = new SqlCommand(insertDetail, con);
                cmdDetail.Parameters.AddWithValue("@id", Guid.NewGuid().ToString().Substring(0,10));
                cmdDetail.Parameters.AddWithValue("@prescId", prescriptionId);
                cmdDetail.Parameters.AddWithValue("@medId", (object)medId ?? DBNull.Value);
                cmdDetail.Parameters.AddWithValue("@dosage", dosage);
                cmdDetail.ExecuteNonQuery();
            }

            // update appointment note to mark completed
            string update = "UPDATE appoinment SET note='Completed' WHERE appointmentID=@id";
            SqlCommand cmd2 = new SqlCommand(update, con);
            cmd2.Parameters.AddWithValue("@id", AppointmentID.ToString());
            cmd2.ExecuteNonQuery();

            con.Close();
            MessageBox.Show("Prescription saved successfully.", "Saved", MessageBoxButtons.OK, MessageBoxIcon.Information);
            this.Close();
        }
    }
}
